### ISSUE TITLE
Add json object as return type for get_job_results

### ISSUE THREAD

**Issue by francesconazzaro** [ecmwf-projects/ogc-api-processes-fastapi#35]
In order to return an abstract remote object as a result we need to support a JSON object as a return type for `get_job_results`.

More specifically `ogc_api_processes_fastapi.models.Link` misses a `contentLength` field that is a requirement from ECMWF. @alexamici and I evaluated how to add this field to the API and the solution seems to be an abstract JSON object.

**Comment by alexamici** [comment]
@mcucchi9 you can close this, no?

**Comment by mcucchi9** [comment]
Closed with https://github.com/ecmwf-projects/ogc-api-processes-fastapi/pull/36
